### ISSUE TITLE
clive doesn't work at all.

### ISSUE THREAD

**Issue by pateljoel** [koki-develop/clive#117] opened 2024-01-01 14:18 UTC
Clive doesn't work for me, I tried to run the examples and the browser terminal doesn't perform the actions I want it to.

This seems to be a bug / glitch in clive.

**Comment by koki-develop** [comment] 2024-01-01 23:44
@pateljoel 
Could you please tell me the versions of clive and ttyd you have installed?

```console
$ clive --version
$ ttyd --version
```

**Comment by pateljoel** [comment] 2024-01-02 00:48
All the latest versions.

ttyd: 1.4.7 (brew)
clive: 0.12.8 (brew)

Followed the instructions in the README and I'm on a Mac.

Thanks.

**Comment by koki-develop** [comment] 2024-01-02 02:16
@pateljoel 
Thank you.

Hmm, are there any error logs?
Also, could you describe the specific behavior you're experiencing? For example, the browser doesn't even start, the browser starts but then nothing happens, etc.

**Comment by pateljoel** [comment] 2024-01-02 12:03
@koki-develop As soon as I run `clive start` it opens the browser and when I run the steps in clive inside of the terminal, clive executes the steps but the command line output does not show up in the browser. It only shows the login prompt.

I am using Chrome on Mac latest (120.0.6099.129).

**Comment by koki-develop** [comment] 2024-01-02 13:49
@pateljoel 
Thank you, I was able to reproduce the issue in my environment as well.
I will work on resolving it when I have some time.

**Comment by koki-develop** [comment] 2024-01-02 14:22
@pateljoel 
I've released version 0.12.9 which fixes the issue, so please give it a try!

- https://github.com/koki-develop/clive/releases/tag/v0.12.9

It seems that the problem was caused by a breaking change in the latest version of ttyd.
Thank you for your report!

**Closed** 2024-01-02 14:23 UTC
